

export const memberDemographics = [
  { name: '18-25', value: 301, fill: 'hsl(252 82% 64%)' },
  { name: '26-40', value: 421, fill: 'hsl(217 91% 60%)' },
  { name: '41-60', value: 241, fill: 'hsl(45 93% 58%)' },
  { name: '60+', value: 241, fill: 'hsl(142 71% 45%)' },
];

export const memberGrowthData = [
    { month: 'Ene', members: 2100 },
    { month: 'Feb', members: 2120 },
    { month: 'Mar', members: 2150 },
    { month: 'Abr', members: 2180 },
    { month: 'May', members: 2210 },
    { month: 'Jun', members: 2240 },
    { month: 'Jul', members: 2270 },
    { month: 'Ago', members: 2290 },
    { month: 'Sep', members: 2310 },
    { month: 'Oct', members: 2330 },
    { month: 'Nov', members: 2340 },
    { month: 'Dic', members: 2350 },
];

export const attendanceData = [
    // Year Data
    { week: 1, month: 'Ene', attendance: 420 }, { week: 2, month: 'Ene', attendance: 430 }, { week: 3, month: 'Ene', attendance: 440 }, { week: 4, month: 'Ene', attendance: 450 },
    { week: 5, month: 'Feb', attendance: 460 }, { week: 6, month: 'Feb', attendance: 455 }, { week: 7, month: 'Feb', attendance: 465 }, { week: 8, month: 'Feb', attendance: 470 },
    { week: 9, month: 'Mar', attendance: 475 }, { week: 10, month: 'Mar', attendance: 480 }, { week: 11, month: 'Mar', attendance: 485 }, { week: 12, month: 'Mar', attendance: 490 },
    { week: 13, month: 'Abr', attendance: 495 }, { week: 14, month: 'Abr', attendance: 500 }, { week: 15, month: 'Abr', attendance: 505 }, { week: 16, month: 'Abr', attendance: 510 },
    { week: 17, month: 'May', attendance: 515 }, { week: 18, month: 'May', attendance: 520 }, { week: 19, month: 'May', attendance: 525 }, { week: 20, month: 'May', attendance: 530 },
    { week: 21, month: 'Jun', attendance: 535 }, { week: 22, month: 'Jun', attendance: 540 }, { week: 23, month: 'Jun', attendance: 545 }, { week: 24, month: 'Jun', attendance: 550 },
    { week: 25, month: 'Jul', attendance: 555 }, { week: 26, month: 'Jul', attendance: 560 }, { week: 27, month: 'Jul', attendance: 565 }, { week: 28, month: 'Jul', attendance: 570 },
    { week: 29, month: 'Ago', attendance: 575 }, { week: 30, month: 'Ago', attendance: 580 }, { week: 31, month: 'Ago', attendance: 585 }, { week: 32, month: 'Ago', attendance: 590 },
    { week: 33, month: 'Sep', attendance: 595 }, { week: 34, month: 'Sep', attendance: 600 }, { week: 35, month: 'Sep', attendance: 605 }, { week: 36, month: 'Sep', attendance: 610 },
    { week: 37, month: 'Oct', attendance: 615 }, { week: 38, month: 'Oct', attendance: 620 }, { week: 39, month: 'Oct', attendance: 625 }, { week: 40, month: 'Oct', attendance: 630 },
    { week: 41, month: 'Nov', attendance: 635 }, { week: 42, month: 'Nov', attendance: 640 }, { week: 43, month: 'Nov', attendance: 645 }, { week: 44, month: 'Nov', attendance: 650 },
    { week: 45, month: 'Dic', attendance: 655 }, { week: 46, month: 'Dic', attendance: 660 }, { week: 47, month: 'Dic', attendance: 665 }, { week: 48, month: 'Dic', attendance: 670 },
    { week: 49, month: 'Dic', attendance: 675 }, { week: 50, month: 'Dic', attendance: 680 }, { week: 51, month: 'Dic', attendance: 685 }, { week: 52, month: 'Dic', attendance: 458 },
];

export const givingData = [
    // 2022 Data
    { year: 2022, month: 'Ene', total: 9500, newVisitors: 12 },
    { year: 2022, month: 'Feb', total: 10200, newVisitors: 15 },
    { year: 2022, month: 'Mar', total: 12100, newVisitors: 18 },
    { year: 2022, month: 'Abr', total: 11800, newVisitors: 16 },
    { year: 2022, month: 'May', total: 14780, newVisitors: 22 },
    { year: 2022, month: 'Jun', total: 11450, newVisitors: 20 },
    { year: 2022, month: 'Jul', total: 15200, newVisitors: 25 },
    { year: 2022, month: 'Ago', total: 13800, newVisitors: 24 },
    { year: 2022, month: 'Sep', total: 16500, newVisitors: 28 },
    { year: 2022, month: 'Oct', total: 17100, newVisitors: 30 },
    { year: 2022, month: 'Nov', total: 18500, newVisitors: 33 },
    { year: 2022, month: 'Dic', total: 21450, newVisitors: 38 },
    // 2023 Data
    { year: 2023, month: 'Ene', total: 10500, newVisitors: 15 },
    { year: 2023, month: 'Feb', total: 11200, newVisitors: 18 },
    { year: 2023, month: 'Mar', total: 13100, newVisitors: 22 },
    { year: 2023, month: 'Abr', total: 12800, newVisitors: 20 },
    { year: 2023, month: 'May', total: 15780, newVisitors: 25 },
    { year: 2023, month: 'Jun', total: 12450, newVisitors: 23 },
    { year: 2023, month: 'Jul', total: 16200, newVisitors: 28 },
    { year: 2023, month: 'Ago', total: 14800, newVisitors: 26 },
    { year: 2023, month: 'Sep', total: 17500, newVisitors: 30 },
    { year: 2023, month: 'Oct', total: 18100, newVisitors: 32 },
    { year: 2023, month: 'Nov', total: 19500, newVisitors: 35 },
    { year: 2023, month: 'Dic', total: 22450, newVisitors: 40 },
    // 2024 Data
    { year: 2024, month: 'Ene', total: 11500, newVisitors: 18 },
    { year: 2024, month: 'Feb', total: 12200, newVisitors: 20 },
    { year: 2024, month: 'Mar', total: 14100, newVisitors: 25 },
    { year: 2024, month: 'Abr', total: 13800, newVisitors: 22 },
    { year: 2024, month: 'May', total: 16780, newVisitors: 28 },
    { year: 2024, month: 'Jun', total: 13450, newVisitors: 25 },
    { year: 2024, month: 'Jul', total: 17200, newVisitors: 30 },
    { year: 2024, month: 'Ago', total: 15800, newVisitors: 28 },
    { year: 2024, month: 'Sep', total: 18500, newVisitors: 32 },
    { year: 2024, month: 'Oct', total: 19100, newVisitors: 35 },
    { year: 2024, month: 'Nov', total: 20500, newVisitors: 38 },
    { year: 2024, month: 'Dic', total: 23450, newVisitors: 42 },
];


export const upcomingEvents = [
  {
    title: 'Servicio Dominical Matutino',
    date: 'JUN 23',
    time: '10:00 AM',
    location: 'Santuario Principal',
  },
  {
    title: 'Reunión de Jóvenes',
    date: 'JUN 26',
    time: '6:30 PM',
    location: 'Salón de Jóvenes',
  },
  {
    title: 'Colecta de Alimentos Comunitari',
    date: 'JUN 29',
    time: '9:00 AM',
    location: 'Estacionamiento de la Iglesia',
  },
  {
    title: "Desayuno de Hombres",
    date: 'JUL 01',
    time: '8:00 AM',
    location: 'Salón de Confraternidad',
  },
];

export const prayerRequests = [
    { id: 1, request: 'Sanidad para María S.', submitted: 'Enviado hace 2 días' },
    { id: 2, request: 'Guía para la Familia Johnson', submitted: 'Enviado hace 3 días' },
    { id: 3, request: 'Oportunidad de trabajo para David P.', submitted: 'Enviado hace 5 días' },
];

export const membersData = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      phone1: '+1 234 567 890',
      phone2: '',
      status: 'Activo',
      groups: ['Voluntarios', 'Coro'],
    },
    {
      id: 2,
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      phone1: '+1 987 654 321',
      phone2: '',
      status: 'Activo',
      groups: ['Grupo de Jóvenes'],
    },
    {
      id: 3,
      name: 'Robert Brown',
      email: 'robert.brown@example.com',
      phone1: '+1 555 123 456',
      phone2: '',
      status: 'Visitante',
      groups: ['Nuevo Miembro'],
    },
    {
      id: 4,
      name: 'Emily Davis',
      email: 'emily.davis@example.com',
      phone1: '+1 444 555 666',
      phone2: '',
      status: 'Activo',
      groups: ['Voluntarios'],
    },
    {
      id: 5,
      name: 'Michael Wilson',
      email: 'michael.wilson@example.com',
      phone1: '+1 777 888 999',
      phone2: '',
      status: 'Inactivo',
      groups: [],
    },
    { id: 6, name: 'Sophia Martinez', email: 'sophia.martinez@example.com', phone1: '+1 555-100-1000', phone2: '', status: 'Activo', groups: ['Coro', 'Voluntarios'] },
    { id: 7, name: 'James Johnson', email: 'james.johnson@example.com', phone1: '+1 555-101-1010', phone2: '', status: 'Inactivo', groups: [] },
    { id: 8, name: 'Olivia Garcia', email: 'olivia.garcia@example.com', phone1: '+1 555-102-1020', phone2: '', status: 'Visitante', groups: ['Nuevo Miembro'] },
    { id: 9, name: 'Liam Rodriguez', email: 'liam.rodriguez@example.com', phone1: '+1 555-103-1030', phone2: '', status: 'Activo', groups: ['Grupo de Jóvenes'] },
    { id: 10, name: 'Emma Lopez', email: 'emma.lopez@example.com', phone1: '+1 555-104-1040', phone2: '', status: 'Activo', groups: ['Voluntarios'] },
    { id: 11, name: 'Noah Hernandez', email: 'noah.hernandez@example.com', phone1: '+1 555-105-1050', phone2: '', status: 'Inactivo', groups: [] },
    { id: 12, name: 'Ava Gonzalez', email: 'ava.gonzalez@example.com', phone1: '+1 555-106-1060', phone2: '', status: 'Activo', groups: ['Coro'] },
    { id: 13, name: 'William Perez', email: 'william.perez@example.com', phone1: '+1 555-107-1070', phone2: '', status: 'Visitante', groups: ['Nuevo Miembro'] },
    { id: 14, name: 'Isabella Sanchez', email: 'isabella.sanchez@example.com', phone1: '+1 555-108-1080', phone2: '', status: 'Activo', groups: ['Grupo de Jóvenes', 'Voluntarios'] },
    { id: 15, name: 'James Ramirez', email: 'james.ramirez@example.com', phone1: '+1 555-109-1090', phone2: '', status: 'Activo', groups: ['Voluntarios'] },
    { id: 16, name: 'Charlotte Torres', email: 'charlotte.torres@example.com', phone1: '+1 555-110-1100', phone2: '', status: 'Activo', groups: ['Coro'] },
    { id: 17, name: 'Benjamin Flores', email: 'benjamin.flores@example.com', phone1: '+1 555-111-1110', phone2: '', status: 'Inactivo', groups: [] },
    { id: 18, name: 'Amelia Rivera', email: 'amelia.rivera@example.com', phone1: '+1 555-112-1120', phone2: '', status: 'Visitante', groups: ['Nuevo Miembro'] },
    { id: 19, name: 'Lucas Gomez', email: 'lucas.gomez@example.com', phone1: '+1 555-113-1130', phone2: '', status: 'Activo', groups: ['Grupo de Jóvenes'] },
    { id: 20, name: 'Mia Diaz', email: 'mia.diaz@example.com', phone1: '+1 555-114-1140', phone2: '', status: 'Activo', groups: ['Voluntarios'] },
    { id: 21, name: 'Henry Cruz', email: 'henry.cruz@example.com', phone1: '+1 555-115-1150', phone2: '', status: 'Activo', groups: ['Coro', 'Voluntarios'] },
    { id: 22, name: 'Evelyn Reyes', email: 'evelyn.reyes@example.com', phone1: '+1 555-116-1160', phone2: '', status: 'Inactivo', groups: [] },
    { id: 23, name: 'Alexander Morales', email: 'alexander.morales@example.com', phone1: '+1 555-117-1170', phone2: '', status: 'Visitante', groups: ['Nuevo Miembro'] },
    { id: 24, name: 'Harper Gutierrez', email: 'harper.gutierrez@example.com', phone1: '+1 555-118-1180', phone2: '', status: 'Activo', groups: ['Grupo de Jóvenes'] },
    { id: 25, name: 'Sebastian Ortiz', email: 'sebastian.ortiz@example.com', phone1: '+1 555-119-1190', phone2: '', status: 'Activo', groups: ['Voluntarios'] },
    { id: 26, name: 'Camila Jimenez', email: 'camila.jimenez@example.com', phone1: '+1 555-120-1200', phone2: '', status: 'Inactivo', groups: [] },
    { id: 27, name: 'Daniel Moreno', email: 'daniel.moreno@example.com', phone1: '+1 555-121-1210', phone2: '', status: 'Activo', groups: ['Coro'] },
    { id: 28, name: 'Sofia Castillo', email: 'sofia.castillo@example.com', phone1: '+1 555-122-1220', phone2: '', status: 'Visitante', groups: ['Nuevo Miembro'] },
    { id: 29, name: 'Matthew Vasquez', email: 'matthew.vasquez@example.com', phone1: '+1 555-123-1230', phone2: '', status: 'Activo', groups: ['Grupo de Jóvenes', 'Voluntarios'] },
    { id: 30, name: 'Avery Chavez', email: 'avery.chavez@example.com', phone1: '+1 555-124-1240', phone2: '', status: 'Activo', groups: ['Voluntarios'] },
    { id: 31, name: 'David Mendoza', email: 'david.mendoza@example.com', phone1: '+1 555-125-1250', phone2: '', status: 'Activo', groups: ['Coro'] },
    { id: 32, name: 'Ella Medina', email: 'ella.medina@example.com', phone1: '+1 555-126-1260', phone2: '', status: 'Inactivo', groups: [] },
    { id: 33, name: 'Joseph Rojas', email: 'joseph.rojas@example.com', phone1: '+1 555-127-1270', phone2: '', status: 'Visitante', groups: ['Nuevo Miembro'] },
    { id: 34, name: 'Scarlett Guerrero', email: 'scarlett.guerrero@example.com', phone1: '+1 555-128-1280', phone2: '', status: 'Activo', groups: ['Grupo de Jóvenes'] },
    { id: 35, name: 'Samuel Pena', email: 'samuel.pena@example.com', phone1: '+1 555-129-1290', phone2: '', status: 'Activo', groups: ['Voluntarios'] },
    { id: 36, name: 'Grace Soto', email: 'grace.soto@example.com', phone1: '+1 555-130-1300', phone2: '', status: 'Activo', groups: ['Coro', 'Voluntarios'] },
    { id: 37, name: 'Jackson Alvarado', email: 'jackson.alvarado@example.com', phone1: '+1 555-131-1310', phone2: '', status: 'Inactivo', groups: [] },
    { id: 38, name: 'Chloe Santos', email: 'chloe.santos@example.com', phone1: '+1 555-132-1320', phone2: '', status: 'Visitante', groups: ['Nuevo Miembro'] },
    { id: 39, name: 'Jayden Garza', email: 'jayden.garza@example.com', phone1: '+1 555-133-1330', phone2: '', status: 'Activo', groups: ['Grupo de Jóvenes'] },
    { id: 40, name: 'Lily Vega', email: 'lily.vega@example.com', phone1: '+1 555-134-1340', phone2: '', status: 'Activo', groups: ['Voluntarios'] },
    { id: 41, name: 'Carter Navarro', email: 'carter.navarro@example.com', phone1: '+1 555-135-1350', phone2: '', status: 'Activo', groups: ['Coro'] }
  ];

  export const groupData = [
    {
      id: 1,
      name: 'Grupo de Jóvenes',
      members: 12,
      description: 'Reunión semanal para adolescentes y jóvenes.',
      status: 'Activo',
    },
    {
      id: 2,
      name: 'Coro',
      members: 25,
      description: 'Dirige la adoración a través de la música los domingos.',
      status: 'Activo',
    },
    {
      id: 3,
      name: 'Voluntarios',
      members: 58,
      description: 'Grupo de voluntarios generales para eventos y necesidades de la iglesia.',
      status: 'Activo',
    },
    {
      id: 4,
      name: "Estudio Bíblico de Hombres",
      members: 8,
      description: 'Sesiones de estudio quincenales para hombres.',
      status: 'En Pausa',
    },
    {
      id: 5,
      name: 'Clase de Nuevos Miembros',
      members: 15,
      description: 'Clase de orientación para nuevos miembros de la iglesia.',
      status: 'Inactivo',
    },
  ];
  
  export const groupMembers = [
    {
      id: 1,
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      phone: '+1 987 654 321',
      role: 'Líder',
    },
    {
      id: 2,
      name: 'Emily White',
      email: 'emily.white@example.com',
      phone: '+1 234 567 891',
      role: 'Miembro',
    },
    {
      id: 3,
      name: 'Michael Johnson',
      email: 'michael.j@example.com',
      phone: '+1 555 123 457',
      role: 'Miembro',
    },
  ];

  export const attendanceRecords = [
    {
        id: 1,
        date: '2024-10-27',
        serviceName: 'Servicio Dominical',
        memberName: 'John Doe',
        status: 'Presente',
        checkInTime: '10:05 AM',
    },
    {
        id: 2,
        date: '2024-10-27',
        serviceName: 'Servicio Dominical',
        memberName: 'Jane Smith',
        status: 'Presente',
        checkInTime: '10:02 AM',
    },
    {
        id: 3,
        date: '2024-10-26',
        serviceName: 'Reunión de Jóvenes',
        memberName: 'Michael Brown',
        status: 'Ausente',
        checkInTime: '-',
    },
    {
        id: 4,
        date: '2024-10-24',
        serviceName: 'Estudio Bíblico Semanal',
        memberName: 'Emily Johnson',
        status: 'Justificado',
        checkInTime: '-',
    },
    {
        id: 5,
        date: '2024-10-24',
        serviceName: 'Estudio Bíblico Semanal',
        memberName: 'David Wilson',
        status: 'Presente',
        checkInTime: '7:10 PM',
    },
    {
        id: 6,
        date: '2024-10-20',
        serviceName: 'Servicio Dominical',
        memberName: 'John Doe',
        status: 'Presente',
        checkInTime: '10:03 AM',
      },
      {
        id: 7,
        date: '2024-10-20',
        serviceName: 'Servicio Dominical',
        memberName: 'Jane Smith',
        status: 'Presente',
        checkInTime: '10:01 AM',
      },
      {
        id: 8,
        date: '2024-10-19',
        serviceName: 'Reunión de Jóvenes',
        memberName: 'Michael Brown',
        status: 'Presente',
        checkInTime: '7:05 PM',
      },
      {
        id: 9,
        date: '2024-10-17',
        serviceName: 'Estudio Bíblico Semanal',
        memberName: 'Emily Johnson',
        status: 'Ausente',
        checkInTime: '-',
      },
      {
        id: 10,
        date: '2024-10-17',
        serviceName: 'Estudio Bíblico Semanal',
        memberName: 'David Wilson',
        status: 'Presente',
        checkInTime: '7:08 PM',
      },
  ];

  export const events = [
    {
      id: 1,
      title: 'Grupo de Jóvenes',
      category: 'Grupo de Jóvenes',
      date: '2024-10-04T18:30:00',
      time: '6:30 PM - 8:00 PM',
      location: 'Salón de Jóvenes',
      address: '123 Church Street, Anytown, USA',
      description: 'Una noche divertida para que los adolescentes se conecten y crezcan en su fe.'
    },
    {
      id: 2,
      title: 'Servicio Dominical',
      category: 'Servicio Dominical',
      date: '2024-10-06T10:00:00',
      time: '10:00 AM - 11:30 AM',
      location: 'Santuario Principal',
      address: '123 Church Street, Anytown, USA',
      description: 'Únase a nosotros para nuestro servicio de adoración semanal.'
    },
    {
      id: 3,
      title: 'Grupo de Estudio Bíblico Semanal',
      category: 'Estudio Bíblico',
      date: '2024-10-11T19:00:00',
      time: '7:00 PM - 8:30 PM',
      location: 'Salón de Confraternidad',
      address: '123 Church Street, Anytown, USA',
      description: "Únase a nosotros para un estudio en profundidad del libro de Romanos. Todos son bienvenidos, desde nuevos creyentes hasta eruditos experimentados. Es una gran oportunidad para la confraternidad y para crecer en su fe."
    },
    {
      id: 4,
      title: 'Alcance Comunitario',
      category: 'Alcance Comunitario',
      date: '2024-10-10T09:00:00',
      time: '9:00 AM - 12:00 PM',
      location: 'Parque de la Ciudad',
      address: '456 Park Avenue, Anytown, USA',
      description: 'Sirviendo a nuestra comunidad limpiando el parque local.'
    },
    {
      id: 5,
      title: 'Servicio Dominical',
      category: 'Servicio Dominical',
      date: '2024-10-13T10:00:00',
      time: '10:00 AM - 11:30 AM',
      location: 'Santuario Principal',
      address: '123 Church Street, Anytown, USA',
      description: 'Únase a nosotros para nuestro servicio de adoración semanal.'
    }
  ];

  export const volunteersData = [
    {
      id: 1,
      name: 'Olivia Chen',
      role: 'Líder del Grupo de Jóvenes',
      email: 'olivia.chen@example.com',
      phone: '(555) 123-4567',
      hoursServed: 128,
      nextServing: '29 de Oct, 2023',
      backgroundCheck: 'Aprobado',
      avatarUrl: 'https://picsum.photos/seed/101/100/100',
      skills: ['Cuidado de Niños', 'Liderazgo', 'Oratoria', 'Certificado en Primeros Auxilios'],
      availability: {
        Domingo: [{ time: 'Mañanas', available: true }, { time: 'Tardes', available: false }],
        Miércoles: [{ time: 'Noches', available: true }],
        Sábado: [{ time: 'Todo el día', available: true }],
      },
      adminNotes: 'Olivia es un miembro central del equipo de liderazgo juvenil. Excelente con los adolescentes y muy confiable.',
    },
    {
      id: 2,
      name: 'Liam Rodriguez',
      role: 'Técnico de AV',
      email: 'liam.r@example.com',
      phone: '(555) 987-6543',
      hoursServed: 250,
      nextServing: '5 de Nov, 2023',
      backgroundCheck: 'Aprobado',
      avatarUrl: 'https://picsum.photos/seed/102/100/100',
      skills: ['Ingeniería de Audio', 'Producción de Video', 'Iluminación'],
      availability: {
        Domingo: [{ time: 'Mañanas', available: true }, { time: 'Tardes', available: true }],
        Miércoles: [{ time: 'Noches', available: false }],
        Sábado: [{ time: 'Mañanas', available: true }],
      },
      adminNotes: '',
    },
    {
        id: 3,
        name: 'Ava Nguyen',
        role: 'Equipo de Adoración',
        email: 'ava.n@example.com',
        phone: '(555) 234-5678',
        hoursServed: 312,
        nextServing: '29 de Oct, 2023',
        backgroundCheck: 'Aprobado',
        avatarUrl: 'https://picsum.photos/seed/103/100/100',
        skills: ['Voz', 'Guitarra', 'Composición de Canciones'],
        availability: {
          Domingo: [{ time: 'Mañanas', available: true }, { time: 'Tardes', available: false }],
          Miércoles: [{ time: 'Noches', available: true }],
          Sábado: [{ time: 'Todo el día', available: false }],
        },
        adminNotes: 'Dirige la adoración una vez al mes.',
      },
      {
        id: 4,
        name: 'Noah Patel',
        role: 'Anfitrión',
        email: 'noah.p@example.com',
        phone: '(555) 345-6789',
        hoursServed: 85,
        nextServing: '12 de Nov, 2023',
        backgroundCheck: 'Aprobado',
        avatarUrl: 'https://picsum.photos/seed/104/100/100',
        skills: ['Hospitalidad', 'Comunicación'],
        availability: {
          Domingo: [{ time: 'Mañanas', available: true }, { time: 'Tardes', available: false }],
          Miércoles: [{ time: 'Noches', available: false }],
          Sábado: [{ time: 'Todo el día', available: true }],
        },
        adminNotes: 'Muy amigable y acogedor.',
      },
      {
        id: 5,
        name: 'Emma Garcia',
        role: "Ministerio de Niños",
        email: 'emma.g@example.com',
        phone: '(555) 456-7890',
        hoursServed: 190,
        nextServing: '29 de Oct, 2023',
        backgroundCheck: 'Aprobado',
        avatarUrl: 'https://picsum.photos/seed/105/100/100',
        skills: ['Cuidado de Niños', 'Enseñanza', 'Manualidades'],
        availability: {
          Domingo: [{ time: 'Mañanas', available: true }, { time: 'Tardes', available: false }],
          Miércoles: [{ time: 'Noches', available: false }],
          Sábado: [{ time: 'Todo el día', available: false }],
        },
        adminNotes: 'Excelente con los preescolares.',
      },
  ];

  export const sermonsData = [
    {
        id: 1,
        title: 'El Poder del Perdón',
        speaker: 'Pastor John Doe',
        series: 'Evangelio de Juan',
        date: '29 de Oct, 2023',
        status: 'Publicado',
    },
    {
        id: 2,
        title: 'Fe en Acción',
        speaker: 'Pastora Jane Smith',
        series: 'Libro de Santiago',
        date: '05 de Nov, 2023',
        status: 'Programado',
    },
    {
        id: 3,
        title: 'Viviendo con Propósito',
        speaker: 'Orador Invitado Mark',
        series: 'Evento Especial',
        date: '22 de Oct, 2023',
        status: 'Borrador',
    },
    {
        id: 4,
        title: 'El Hijo Pródigo',
        speaker: 'Pastor John Doe',
        series: 'Parábolas de Jesús',
        date: '17 de Sep, 2023',
        status: 'Archivado',
    },
    { id: 5, title: 'Amor y Gracia', speaker: 'Pastor John Doe', series: 'Evangelio de Juan', date: '12 de Nov, 2023', status: 'Publicado' },
    { id: 6, title: 'La Alegría del Señor', speaker: 'Pastora Jane Smith', series: 'Filipenses', date: '19 de Nov, 2023', status: 'Programado' },
    { id: 7, title: 'Sabiduría Divina', speaker: 'Pastor John Doe', series: 'Proverbios', date: '26 de Nov, 2023', status: 'Publicado' },
    { id: 8, title: 'Paz en la Tormenta', speaker: 'Pastora Jane Smith', series: 'Salmos', date: '03 de Dic, 2023', status: 'Programado' },
    { id: 9, title: 'El Gozo de Dar', speaker: 'Pastor John Doe', series: 'Corintios', date: '10 de Dic, 2023', status: 'Borrador' },
    { id: 10, title: 'La Venida de Cristo', speaker: 'Pastora Jane Smith', series: 'Adviento', date: '17 de Dic, 2023', status: 'Programado' },
    { id: 11, title: 'Noche de Paz', speaker: 'Pastor John Doe', series: 'Adviento', date: '24 de Dic, 2023', status: 'Publicado' },
    { id: 12, title: 'Un Nuevo Comienzo', speaker: 'Pastora Jane Smith', series: 'Año Nuevo', date: '31 de Dic, 2023', status: 'Archivado' },
    { id: 13, title: 'Fundamentos de la Fe', speaker: 'Pastor John Doe', series: 'Fundamentos', date: '07 de Ene, 2024', status: 'Publicado' },
    { id: 14, title: 'El Fruto del Espíritu', speaker: 'Pastora Jane Smith', series: 'Gálatas', date: '14 de Ene, 2024', status: 'Publicado' },
    { id: 15, title: 'Andando en el Espíritu', speaker: 'Pastor John Doe', series: 'Gálatas', date: '21 de Ene, 2024', status: 'Borrador' },
    { id: 16, title: 'Venciendo la Tentación', speaker: 'Pastora Jane Smith', series: 'Enseñanzas de Jesús', date: '28 de Ene, 2024', status: 'Publicado' },
    { id: 17, title: 'El Sermón del Monte', speaker: 'Pastor John Doe', series: 'Mateo', date: '04 de Feb, 2024', status: 'Publicado' },
    { id: 18, title: 'Las Bienaventuranzas', speaker: 'Pastor John Doe', series: 'Mateo', date: '11 de Feb, 2024', status: 'Programado' },
    { id: 19, title: 'Sal y Luz', speaker: 'Pastora Jane Smith', series: 'Mateo', date: '18 de Feb, 2024', status: 'Publicado' },
    { id: 20, title: 'Amad a Vuestros Enemigos', speaker: 'Pastor John Doe', series: 'Mateo', date: '25 de Feb, 2024', status: 'Archivado' },
    { id: 21, title: 'El Padre Nuestro', speaker: 'Pastora Jane Smith', series: 'Mateo', date: '03 de Mar, 2024', status: 'Publicado' },
    { id: 22, title: 'Tesoros en el Cielo', speaker: 'Pastor John Doe', series: 'Mateo', date: '10 de Mar, 2024', status: 'Borrador' },
    { id: 23, title: 'No os Afanéis', speaker: 'Pastora Jane Smith', series: 'Mateo', date: '17 de Mar, 2024', status: 'Publicado' },
    { id: 24, title: 'La Regla de Oro', speaker: 'Pastor John Doe', series: 'Mateo', date: '24 de Mar, 2024', status: 'Programado' },
    { id: 25, title: 'La Resurrección', speaker: 'Pastora Jane Smith', series: 'Pascua', date: '31 de Mar, 2024', status: 'Publicado' },
    { id: 26, title: 'La Gran Comisión', speaker: 'Pastor John Doe', series: 'Hechos', date: '07 de Abr, 2024', status: 'Publicado' },
    { id: 27, title: 'El Día de Pentecostés', speaker: 'Pastora Jane Smith', series: 'Hechos', date: '14 de Abr, 2024', status: 'Archivado' },
    { id: 28, title: 'La Iglesia Primitiva', speaker: 'Pastor John Doe', series: 'Hechos', date: '21 de Abr, 2024', status: 'Publicado' },
    { id: 29, title: 'El Mártir Esteban', speaker: 'Pastora Jane Smith', series: 'Hechos', date: '28 de Abr, 2024', status: 'Borrador' },
    { id: 30, title: 'La Conversión de Saulo', speaker: 'Pastor John Doe', series: 'Hechos', date: '05 de May, 2024', status: 'Publicado' },
    { id: 31, title: 'El Viaje Misionero de Pablo', speaker: 'Pastora Jane Smith', series: 'Hechos', date: '12 de May, 2024', status: 'Programado' },
    { id: 32, title: 'Fe y Obras', speaker: 'Pastor John Doe', series: 'Libro de Santiago', date: '19 de May, 2024', status: 'Publicado' },
    { id: 33, title: 'La Lengua', speaker: 'Pastora Jane Smith', series: 'Libro de Santiago', date: '26 de May, 2024', status: 'Archivado' },
    { id: 34, title: 'Humildad y Oración', speaker: 'Pastor John Doe', series: 'Libro de Santiago', date: '02 de Jun, 2024', status: 'Publicado' },
    { id: 35, title: 'El Amor es Paciente', speaker: 'Pastora Jane Smith', series: 'Corintios', date: '09 de Jun, 2024', status: 'Borrador' },
    { id: 36, title: 'Dones Espirituales', speaker: 'Pastor John Doe', series: 'Corintios', date: '16 de Jun, 2024', status: 'Publicado' },
    { id: 37, title: 'La Cena del Señor', speaker: 'Pastora Jane Smith', series: 'Corintios', date: '23 de Jun, 2024', status: 'Programado' },
    { id: 38, title: 'La Armadura de Dios', speaker: 'Pastor John Doe', series: 'Efesios', date: '30 de Jun, 2024', status: 'Publicado' },
    { id: 39, title: 'Andando en Amor', speaker: 'Pastora Jane Smith', series: 'Efesios', date: '07 de Jul, 2024', status: 'Archivado' },
    { id: 40, title: 'Hijos de Luz', speaker: 'Pastor John Doe', series: 'Efesios', date: '14 de Jul, 2024', status: 'Publicado' },
    { id: 41, title: 'Relaciones Piadosas', speaker: 'Pastora Jane Smith', series: 'Efesios', date: '21 de Jul, 2024', status: 'Borrador' },
    { id: 42, title: 'La Mente de Cristo', speaker: 'Pastor John Doe', series: 'Filipenses', date: '28 de Jul, 2024', status: 'Publicado' },
    { id: 43, title: 'Regocijaos en el Señor', speaker: 'Pastora Jane Smith', series: 'Filipenses', date: '04 de Ago, 2024', status: 'Programado' },
    { id: 44, title: 'Todo lo Puedo en Cristo', speaker: 'Pastor John Doe', series: 'Filipenses', date: '11 de Ago, 2024', status: 'Publicado' },
    { id: 45, title: 'La Supremacía de Cristo', speaker: 'Pastora Jane Smith', series: 'Colosenses', date: '18 de Ago, 2024', status: 'Archivado' },
    { id: 46, title: 'Vestidos de Cristo', speaker: 'Pastor John Doe', series: 'Colosenses', date: '25 de Ago, 2024', status: 'Publicado' },
    { id: 47, title: 'Oración y Acción de Gracias', speaker: 'Pastora Jane Smith', series: 'Colosenses', date: '01 de Sep, 2024', status: 'Borrador' },
    { id: 48, title: 'La Segunda Venida', speaker: 'Pastor John Doe', series: 'Tesalonicenses', date: '08 de Sep, 2024', status: 'Publicado' },
    { id: 49, title: 'Viviendo para Agradar a Dios', speaker: 'Pastora Jane Smith', series: 'Tesalonicenses', date: '15 de Sep, 2024', status: 'Programado' },
  ];

  export const rolesData = [
    {
      id: 1,
      name: 'Super Administrador',
      description: 'Acceso completo a todas las funciones y configuraciones del sistema.',
      users: [
        { id: 1, name: 'Usuario A', avatarUrl: 'https://picsum.photos/seed/u1/40/40' },
        { id: 2, name: 'Usuario B', avatarUrl: 'https://picsum.photos/seed/u2/40/40' },
        { id: 3, name: 'Usuario C', avatarUrl: 'https://picsum.photos/seed/u3/40/40' },
        { id: 4, name: 'Usuario D', avatarUrl: 'https://picsum.photos/seed/u4/40/40' },
        { id: 5, name: 'Usuario E', avatarUrl: 'https://picsum.photos/seed/u5/40/40' },
        { id: 6, name: 'Usuario F', avatarUrl: 'https://picsum.photos/seed/u6/40/40' },
      ],
    },
    {
      id: 2,
      name: 'Pastor',
      description: 'Acceso a datos de miembros, eventos y gestión de sermones.',
      users: [{ id: 7, name: 'Usuario G', avatarUrl: 'https://picsum.photos/seed/u7/40/40' },
        { id: 8, name: 'Usuario H', avatarUrl: 'https://picsum.photos/seed/u8/40/40' },
    ],
    },
    {
      id: 3,
      name: 'Personal de Oficina',
      description: 'Maneja tareas administrativas diarias y registros de miembros.',
      users: [
        { id: 9, name: 'Usuario I', avatarUrl: 'https://picsum.photos/seed/u9/40/40' },
        { id: 10, name: 'Usuario J', avatarUrl: 'https://picsum.photos/seed/u10/40/40' },
        { id: 11, name: 'Usuario K', avatarUrl: 'https://picsum.photos/seed/u11/40/40' },
        { id: 12, name: 'Usuario L', avatarUrl: 'https://picsum.photos/seed/u12/40/40' },
        { id: 13, name: 'Usuario M', avatarUrl: 'https://picsum.photos/seed/u13/40/40' },
        { id: 14, name: 'Usuario N', avatarUrl: 'https://picsum.photos/seed/u14/40/40' },
        { id: 15, name: 'Usuario O', avatarUrl: 'https://picsum.photos/seed/u15/40/40' },
        { id: 16, name: 'Usuario P', avatarUrl: 'https://picsum.photos/seed/u16/40/40' },
        { id: 17, name: 'Usuario Q', avatarUrl: 'https://picsum.photos/seed/u17/40/40' },
        { id: 18, name: 'Usuario R', avatarUrl: 'https://picsum.photos/seed/u18/40/40' },
      ],
    },
    {
      id: 4,
      name: 'Líder de Grupo Pequeño',
      description: 'Gestiona grupos pequeños específicos y comunicaciones relacionadas.',
      users: Array.from({ length: 15 }, (_, i) => ({
        id: 19 + i,
        name: `Usuario ${String.fromCharCode(83 + i)}`,
        avatarUrl: `https://picsum.photos/seed/u${19 + i}/40/40`,
      })),
    },
    {
      id: 5,
      name: 'Miembro',
      description: 'Acceso básico al perfil personal e información general de la iglesia.',
      users: 350,
    },
  ];

  export const allUsers = [
    { id: 1, name: 'Admin User', email: 'admin@example.com', role: 'Super Administrador', avatarUrl: 'https://picsum.photos/seed/u1/40/40' },
    { id: 2, name: 'Pastor John', email: 'pastor.j@example.com', role: 'Pastor', avatarUrl: 'https://picsum.photos/seed/u7/40/40' },
    { id: 3, name: 'Sarah Miller', email: 'sarah.m@example.com', role: 'Personal de Oficina', avatarUrl: 'https://picsum.photos/seed/u9/40/40' },
    { id: 4, name: 'David Chen', email: 'david.c@example.com', role: 'Líder de Grupo Pequeño', avatarUrl: 'https://picsum.photos/seed/u19/40/40' },
    { id: 5, name: 'Regular Member', email: 'member@example.com', role: 'Miembro', avatarUrl: 'https://picsum.photos/seed/u34/40/40' },
    { id: 6, name: 'Betty Rubble', email: 'betty@example.com', role: 'Personal de Oficina', avatarUrl: 'https://picsum.photos/seed/u10/40/40' },
    { id: 7, name: 'Fred Flintstone', email: 'fred@example.com', role: 'Líder de Grupo Pequeño', avatarUrl: 'https://picsum.photos/seed/u20/40/40' },
    { id: 8, name: 'Wilma Flintstone', email: 'wilma@example.com', role: 'Líder de Grupo Pequeño', avatarUrl: 'https://picsum.photos/seed/u21/40/40' },
    { id: 9, name: 'Barney Rubble', email: 'barney@example.com', role: 'Miembro', avatarUrl: 'https://picsum.photos/seed/u35/40/40' },
    { id: 10, name: 'Pebbles Flintstone', email: 'pebbles@example.com', role: 'Miembro', avatarUrl: 'https://picsum.photos/seed/u36/40/40' },
    { id: 11, name: 'Bamm-Bamm Rubble', email: 'bammbamm@example.com', role: 'Miembro', avatarUrl: 'https://picsum.photos/seed/u37/40/40' },
  ];

  export const ministriesData = [
    {
      id: 1,
      name: 'Equipo de Adoración',
      description: 'Dirige a la congregación en adoración durante los servicios.',
      members: 15,
      leader: 'John Doe',
      memberAvatars: [
        'https://picsum.photos/seed/m1/40/40',
        'https://picsum.photos/seed/m2/40/40',
        'https://picsum.photos/seed/m3/40/40',
      ],
    },
    {
      id: 2,
      name: 'Grupo de Jóvenes',
      description: 'Mentoría y actividades para adolescentes.',
      members: 32,
      leader: 'Jane Smith',
      memberAvatars: [
        'https://picsum.photos/seed/m4/40/40',
        'https://picsum.photos/seed/m5/40/40',
        'https://picsum.photos/seed/m6/40/40',
      ],
    },
    {
      id: 3,
      name: 'Alcance Comunitario',
      description: 'Sirviendo a la comunidad local a través de varios proyectos.',
      members: 25,
      leader: 'Robert Brown',
      memberAvatars: [
        'https://picsum.photos/seed/m7/40/40',
        'https://picsum.photos/seed/m8/40/40',
        'https://picsum.photos/seed/m9/40/40',
      ],
    },
    {
        id: 4,
        name: "Iglesia de Niños",
        description: 'Escuela dominical y actividades para niños.',
        members: 18,
        leader: 'Susan White',
        memberAvatars: [
            'https://picsum.photos/seed/m10/40/40',
            'https://picsum.photos/seed/m11/40/40',
            'https://picsum.photos/seed/m12/40/40',
        ],
    }
  ];

  export const incomeExpenseData = [
    { month: 'Ene', net: 18000 },
    { month: 'Feb', net: 22000 },
    { month: 'Mar', net: 19000 },
    { month: 'Abr', net: 25000 },
    { month: 'May', net: 23000 },
    { month: 'Jun', net: 28000 },
    { month: 'Jul', net: 31000 },
    { month: 'Ago', net: 29000 },
  ];
  
  export const budgetSpendingData = [
    { name: 'Misiones', spent: 4000, budget: 1000 },
    { name: 'Salarios', spent: 8000, budget: 6000 },
    { name: 'Servicios', spent: 1500, budget: 3500 },
    { name: 'Mant.', spent: 3000, budget: 2000 },
    { name: 'Eventos', spent: 2500, budget: 2500 },
  ];
  
  export const recentTransactions = [
    { id: 1, date: '12 de Ago, 2023', description: 'Diezmos y Ofrendas', category: 'Donación', fund: 'Fondo General', amount: 5250.00 },
    { id: 2, date: '10 de Ago, 2023', description: 'Factura de Electricidad', category: 'Servicios', fund: 'Gastos Operativos', amount: -450.75 },
    { id: 3, date: '08 de Ago, 2023', description: 'Viaje Misionero - México', category: 'Misiones', fund: 'Fondo de Misiones', amount: -2100.00 },
    { id: 4, date: '05 de Ago, 2023', description: 'Diezmos y Ofrendas', category: 'Donación', fund: 'Fondo General', amount: 4820.50 },
    { id: 5, date: '01 de Ago, 2023', description: 'Salarios Pastorales', category: 'Salarios', fund: 'Gastos Operativos', amount: -8500.00 },
  ];

  export const incomeStatementData = {
    income: [
      { label: 'Diezmos y Ofrendas', amount: 125450.75 },
      { label: 'Donaciones para el Fondo de Construcción', amount: 15200.00 },
      { label: 'Inscripciones a Eventos', amount: 3750.00 },
      { label: 'Otros Ingresos', amount: 1120.25 },
    ],
    expenses: [
      { label: 'Salarios Pastorales y de Personal', amount: 68000.00 },
      { label: 'Misiones y Alcance Comunitario', amount: 16800.00 },
      { label: 'Servicios Públicos', amount: 4320.50 },
      { label: 'Mantenimiento de Instalaciones', amount: 7150.00 },
      { label: 'Ministerios y Eventos', amount: 9400.00 },
      { label: 'Costos Administrativos', amount: 2560.25 },
    ],
    totalIncome: 145521.00,
    totalExpenses: 108230.75,
    netIncome: 37290.25,
  };

  export const budgetReportData = {
    totalBudget: 250000,
    totalActual: 253751,
    variance: 3751,
    previousPeriodBudget: 245000,
    income: {
      totalBudget: 145000,
      totalActual: 145521,
      items: [
        { category: 'Diezmos y Ofrendas', budget: 125000, actual: 125450.75 },
        { category: 'Fondo de Construcción', budget: 15000, actual: 15200.00 },
        { category: 'Otros Ingresos', budget: 5000, actual: 4870.25 },
      ]
    },
    expenses: {
      totalBudget: 110000,
      totalActual: 108230.75,
      items: [
        { category: 'Salarios y Beneficios', budget: 70000, actual: 68000 },
        { category: 'Misiones y Alcance Comunitario', budget: 15000, actual: 16800 },
        { category: 'Instalaciones y Servicios Públicos', budget: 12000, actual: 11470.50 },
        { category: 'Ministerios y Eventos', budget: 10000, actual: 9400 },
        { category: 'Costos Administrativos', budget: 3000, actual: 2560.25 },
      ]
    },
    netTotal: {
        budget: 35000,
        actual: 37290.25
    }
  };

  export const fundBalancesData = {
    totalBalance: 576215.80,
    activeFunds: 8,
    totalInflows: 145521.00,
    totalOutflows: 108230.75,
    funds: [
        { name: 'Fondo General', description: 'Fondo operativo principal', type: 'No Restringido', balance: 350120.45, ytdInflows: 125450.75, ytdOutflows: -88960.50, status: 'Activo' },
        { name: 'Fondo de Construcción', description: 'Para la construcción del nuevo santuario', type: 'Designado', balance: 150500.00, ytdInflows: 15200.00, ytdOutflows: 0.00, status: 'Activo' },
        { name: 'Fondo de Misiones', description: 'Apoya misiones globales y locales', type: 'Restringido', balance: 52345.10, ytdInflows: 4870.25, ytdOutflows: -16800.00, status: 'Activo' },
        { name: 'Fondo del Ministerio Juvenil', description: 'Para eventos y actividades juveniles', type: 'Designado', balance: 12850.25, ytdInflows: 0.00, ytdOutflows: -2470.25, status: 'Activo' },
        { name: 'Fondo de Benevolencia', description: 'Asistencia para miembros de la comunidad', type: 'Restringido', balance: 10400.00, ytdInflows: 0.00, ytdOutflows: 0.00, status: 'Activo' },
        { name: "Fondo Discrecional del Pastor", description: 'Apoyo pastoral confidencial', type: 'Designado', balance: 0.00, ytdInflows: 0.00, ytdOutflows: 0.00, status: 'Inactivo' },
    ]
  };

  export const donationReportsData = {
    totalDonations: {
        amount: 18250.75,
        period: 'Este mes'
    },
    averageDonation: {
        amount: 125.69,
        description: 'En 145 donaciones'
    },
    newDonors: {
        amount: 1500.00,
        description: 'De 12 nuevos donantes este mes'
    },
    givingTrends: {
        // Data for chart will go here
    },
    recentDonations: [
        { id: 1, donorName: 'John & Jane Smith', donorEmail: 'john.smith@example.com', date: '28 de Ago, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 250.00 },
        { id: 2, donorName: 'Robert Williams', donorEmail: 'robert.w@example.com', date: '25 de Ago, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 1000.00 },
        { id: 3, donorName: 'Mary Johnson', donorEmail: 'mary.j@example.com', date: '22 de Ago, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 50.00 },
        { id: 4, donorName: 'David Brown', donorEmail: 'david.b@example.com', date: '20 de Ago, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 100.00 },
        { id: 5, donorName: 'Donante Anónimo', donorEmail: 'Donación en Efectivo', date: '18 de Ago, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 20.00 },
        { id: 6, donorName: 'Laura White', donorEmail: 'laura.w@example.com', date: '17 de Ago, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 75.00 },
        { id: 7, donorName: 'James Green', donorEmail: 'james.g@example.com', date: '15 de Ago, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 500.00 },
        { id: 8, donorName: 'Patricia Hall', donorEmail: 'patricia.h@example.com', date: '14 de Ago, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 25.00 },
        { id: 9, donorName: 'Michael Harris', donorEmail: 'michael.h@example.com', date: '12 de Ago, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 200.00 },
        { id: 10, donorName: 'Linda Martin', donorEmail: 'linda.m@example.com', date: '10 de Ago, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 30.00 },
        { id: 11, donorName: 'Richard Taylor', donorEmail: 'richard.t@example.com', date: '09 de Ago, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 150.00 },
        { id: 12, donorName: 'Susan Anderson', donorEmail: 'susan.a@example.com', date: '07 de Ago, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 750.00 },
        { id: 13, donorName: 'Joseph Thomas', donorEmail: 'joseph.t@example.com', date: '05 de Ago, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 40.00 },
        { id: 14, donorName: 'Jessica Jackson', donorEmail: 'jessica.j@example.com', date: '04 de Ago, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 50.00 },
        { id: 15, donorName: 'Donante Anónimo', donorEmail: 'Donación en Efectivo', date: '02 de Ago, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 10.00 },
        { id: 16, donorName: 'Charles Moore', donorEmail: 'charles.m@example.com', date: '01 de Ago, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 300.00 },
        { id: 17, donorName: 'Karen Clark', donorEmail: 'karen.c@example.com', date: '30 de Jul, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 2000.00 },
        { id: 18, donorName: 'Daniel Lewis', donorEmail: 'daniel.l@example.com', date: '28 de Jul, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 60.00 },
        { id: 19, donorName: 'Nancy Lee', donorEmail: 'nancy.l@example.com', date: '26 de Jul, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 120.00 },
        { id: 20, donorName: 'Paul Walker', donorEmail: 'paul.w@example.com', date: '24 de Jul, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 25.00 },
        { id: 21, donorName: 'Mark Young', donorEmail: 'mark.y@example.com', date: '23 de Jul, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 175.00 },
        { id: 22, donorName: 'Betty King', donorEmail: 'betty.k@example.com', date: '21 de Jul, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 300.00 },
        { id: 23, donorName: 'Steven Wright', donorEmail: 'steven.w@example.com', date: '19 de Jul, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 80.00 },
        { id: 24, donorName: 'Sandra Hill', donorEmail: 'sandra.h@example.com', date: '17 de Jul, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 70.00 },
        { id: 25, donorName: 'Donante Anónimo', donorEmail: 'Donación en Efectivo', date: '15 de Jul, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 15.00 },
        { id: 26, donorName: 'George Scott', donorEmail: 'george.s@example.com', date: '14 de Jul, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 220.00 },
        { id: 27, donorName: 'Ashley Green', donorEmail: 'ashley.g@example.com', date: '12 de Jul, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 1500.00 },
        { id: 28, donorName: 'Kevin Adams', donorEmail: 'kevin.a@example.com', date: '10 de Jul, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 35.00 },
        { id: 29, donorName: 'Melissa Baker', donorEmail: 'melissa.b@example.com', date: '08 de Jul, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 90.00 },
        { id: 30, donorName: 'Edward Nelson', donorEmail: 'edward.n@example.com', date: '06 de Jul, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 5.00 },
        { id: 31, donorName: 'Cynthia Carter', donorEmail: 'cynthia.c@example.com', date: '05 de Jul, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 130.00 },
        { id: 32, donorName: 'Ronald Mitchell', donorEmail: 'ronald.m@example.com', date: '03 de Jul, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 600.00 },
        { id: 33, donorName: 'Angela Perez', donorEmail: 'angela.p@example.com', date: '01 de Jul, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 45.00 },
        { id: 34, donorName: 'Brian Roberts', donorEmail: 'brian.r@example.com', date: '30 de Jun, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 110.00 },
        { id: 35, donorName: 'Donante Anónimo', donorEmail: 'Donación en Efectivo', date: '28 de Jun, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 50.00 },
        { id: 36, donorName: 'Kimberly Turner', donorEmail: 'kimberly.t@example.com', date: '27 de Jun, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 180.00 },
        { id: 37, donorName: 'Jason Phillips', donorEmail: 'jason.p@example.com', date: '25 de Jun, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 1200.00 },
        { id: 38, donorName: 'Lisa Campbell', donorEmail: 'lisa.c@example.com', date: '23 de Jun, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 70.00 },
        { id: 39, donorName: 'Jeffrey Parker', donorEmail: 'jeffrey.p@example.com', date: '21 de Jun, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 80.00 },
        { id: 40, donorName: 'Sharon Evans', donorEmail: 'sharon.e@example.com', date: '19 de Jun, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 10.00 },
        { id: 41, donorName: 'Ryan Edwards', donorEmail: 'ryan.e@example.com', date: '18 de Jun, 2023', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 140.00 },
        { id: 42, donorName: 'Donna Collins', donorEmail: 'donna.c@example.com', date: '16 de Jun, 2023', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 800.00 },
        { id: 43, donorName: 'Gary Stewart', donorEmail: 'gary.s@example.com', date: '14 de Jun, 2023', fund: 'Fondo de Misiones', paymentMethod: 'Tarjeta de Crédito', amount: 55.00 },
        { id: 44, donorName: 'Deborah Sanchez', donorEmail: 'deborah.s@example.com', date: '12 de Jun, 2023', fund: 'Fondo General', paymentMethod: 'Cheque', amount: 95.00 },
        { id: 45, donorName: 'Donante Anónimo', donorEmail: 'Donación en Efectivo', date: '10 de Jun, 2023', fund: 'Fondo de Benevolencia', paymentMethod: 'Efectivo', amount: 35.00 },
        { id: 46, donorName: 'Sarah Connor', donorEmail: 'sarah.c@example.com', date: '15 de Ene, 2025', fund: 'Fondo General', paymentMethod: 'Tarjeta de Crédito', amount: 120.00 },
        { id: 47, donorName: 'Kyle Reese', donorEmail: 'kyle.r@example.com', date: '20 de Ene, 2025', fund: 'Fondo de Misiones', paymentMethod: 'Cheque', amount: 75.00 },
        { id: 48, donorName: 'John Connor', donorEmail: 'john.c@example.com', date: '01 de Feb, 2025', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 500.00 },
        { id: 49, donorName: 'T-800', donorEmail: 't800@example.com', date: '05 de Feb, 2025', fund: 'Fondo General', paymentMethod: 'Efectivo', amount: 1000.00 },
        { id: 50, donorName: 'Miles Dyson', donorEmail: 'miles.d@example.com', date: '10 de Mar, 2025', fund: 'Fondo de Benevolencia', paymentMethod: 'Tarjeta de Crédito', amount: 250.00 },
        { id: 51, donorName: 'T-1000', donorEmail: 't1000@example.com', date: '15 de Mar, 2025', fund: 'Fondo de Misiones', paymentMethod: 'Cheque', amount: 200.00 },
        { id: 52, donorName: 'Kate Brewster', donorEmail: 'kate.b@example.com', date: '20 de Abr, 2025', fund: 'Fondo de Construcción', paymentMethod: 'ACH/Transferencia Bancaria', amount: 300.00 },
        { id: 53, donorName: 'Marcus Wright', donorEmail: 'marcus.w@example.com', date: '25 de Abr, 2025', fund: 'Fondo General', paymentMethod: 'Efectivo', amount: 50.00 },
        { id: 54, donorName: 'Serena Kogen', donorEmail: 'serena.k@example.com', date: '01 de May, 2025', fund: 'Fondo de Benevolencia', paymentMethod: 'Tarjeta de Crédito', amount: 150.00 },
        { id: 55, donorName: 'Blair Williams', donorEmail: 'blair.w@example.com', date: '10 de May, 2025', fund: 'Fondo de Misiones', paymentMethod: 'Cheque', amount: 100.00 },
    ]
  }

  export const prayerRequestsData = [
    {
      id: 1,
      title: 'Sanidad para la Madre de Sarah',
      description: 'Orando por la recuperación de una cirugía.',
      submittedBy: 'John Doe',
      submittedByAvatar: 'https://picsum.photos/seed/u1/40/40',
      date: '26 de Oct, 2023',
      status: 'Activo',
      privacy: 'Público',
    },
    {
      id: 2,
      title: 'Guía para un Nuevo Trabajo',
      description: 'Pidiendo sabiduría y claridad.',
      submittedBy: 'Jane Smith',
      submittedByAvatar: 'https://picsum.photos/seed/u2/40/40',
      date: '25 de Oct, 2023',
      status: 'Activo',
      privacy: 'Solo Personal',
    },
    {
      id: 3,
      title: 'Alabanza por el nuevo nieto',
      description: 'El bebé y la madre están sanos.',
      submittedBy: 'Robert Brown',
      submittedByAvatar: 'https://picsum.photos/seed/u3/40/40',
      date: '22 de Oct, 2023',
      status: 'Respondido',
      privacy: 'Público',
    },
  ];

export const memberDonationHistory = [
    { id: 1, date: '2023-10-22', amount: 100.00, fund: 'Fondo General', type: 'Donación en Línea' },
    { id: 2, date: '2023-09-15', amount: 250.00, fund: 'Campaña de Construcción', type: 'Cheque' },
    { id: 3, date: '2023-08-20', amount: 100.00, fund: 'Fondo General', type: 'Donación en Línea' },
    { id: 4, date: '2023-07-18', amount: 50.00, fund: 'Fondo de Misiones', type: 'Efectivo' },
    { id: 5, date: '2023-06-12', amount: 100.00, fund: 'Fondo General', type: 'Donación en Línea' },
    { id: 6, date: '2023-05-21', amount: 500.00, fund: 'Campaña de Construcción', type: 'Transferencia Bancaria' },
];
