export const memberDemographics = [
  { name: 'Children (0-12)', value: 450, fill: 'var(--color-chart-1)' },
  { name: 'Youth (13-18)', value: 300, fill: 'var(--color-chart-2)' },
  { name: 'Young Adults (19-35)', value: 650, fill: 'var(--color-chart-3)' },
  { name: 'Adults (36-60)', value: 700, fill: 'var(--color-chart-4)' },
  { name: 'Seniors (60+)', value: 250, fill: 'var(--color-chart-5)' },
];

export const attendanceData = [
    // Year Data
    { week: 1, month: 'Jan', attendance: 420 }, { week: 2, month: 'Jan', attendance: 430 }, { week: 3, month: 'Jan', attendance: 440 }, { week: 4, month: 'Jan', attendance: 450 },
    { week: 5, month: 'Feb', attendance: 460 }, { week: 6, month: 'Feb', attendance: 455 }, { week: 7, month: 'Feb', attendance: 465 }, { week: 8, month: 'Feb', attendance: 470 },
    { week: 9, month: 'Mar', attendance: 475 }, { week: 10, month: 'Mar', attendance: 480 }, { week: 11, month: 'Mar', attendance: 485 }, { week: 12, month: 'Mar', attendance: 490 },
    { week: 13, month: 'Apr', attendance: 495 }, { week: 14, month: 'Apr', attendance: 500 }, { week: 15, month: 'Apr', attendance: 505 }, { week: 16, month: 'Apr', attendance: 510 },
    { week: 17, month: 'May', attendance: 515 }, { week: 18, month: 'May', attendance: 520 }, { week: 19, month: 'May', attendance: 525 }, { week: 20, month: 'May', attendance: 530 },
    { week: 21, month: 'Jun', attendance: 535 }, { week: 22, month: 'Jun', attendance: 540 }, { week: 23, month: 'Jun', attendance: 545 }, { week: 24, month: 'Jun', attendance: 550 },
    { week: 25, month: 'Jul', attendance: 555 }, { week: 26, month: 'Jul', attendance: 560 }, { week: 27, month: 'Jul', attendance: 565 }, { week: 28, month: 'Jul', attendance: 570 },
    { week: 29, month: 'Aug', attendance: 575 }, { week: 30, month: 'Aug', attendance: 580 }, { week: 31, month: 'Aug', attendance: 585 }, { week: 32, month: 'Aug', attendance: 590 },
    { week: 33, month: 'Sep', attendance: 595 }, { week: 34, month: 'Sep', attendance: 600 }, { week: 35, month: 'Sep', attendance: 605 }, { week: 36, month: 'Sep', attendance: 610 },
    { week: 37, month: 'Oct', attendance: 615 }, { week: 38, month: 'Oct', attendance: 620 }, { week: 39, month: 'Oct', attendance: 625 }, { week: 40, month: 'Oct', attendance: 630 },
    { week: 41, month: 'Nov', attendance: 635 }, { week: 42, month: 'Nov', attendance: 640 }, { week: 43, month: 'Nov', attendance: 645 }, { week: 44, month: 'Nov', attendance: 650 },
    { week: 45, month: 'Dec', attendance: 655 }, { week: 46, month: 'Dec', attendance: 660 }, { week: 47, month: 'Dec', attendance: 665 }, { week: 48, month: 'Dec', attendance: 670 },
    { week: 49, month: 'Dec', attendance: 675 }, { week: 50, month: 'Dec', attendance: 680 }, { week: 51, month: 'Dec', attendance: 685 }, { week: 52, month: 'Dec', attendance: 458 },
];

export const givingData = [
    { month: 'Jan', total: 10500, newVisitors: 15 },
    { month: 'Feb', total: 11200, newVisitors: 18 },
    { month: 'Mar', total: 13100, newVisitors: 22 },
    { month: 'Apr', total: 12800, newVisitors: 20 },
    { month: 'May', total: 15780, newVisitors: 25 },
    { month: 'Jun', total: 12450, newVisitors: 23 },
    { month: 'Jul', total: 16200, newVisitors: 28 },
    { month: 'Aug', total: 14800, newVisitors: 26 },
    { month: 'Sep', total: 17500, newVisitors: 30 },
    { month: 'Oct', total: 18100, newVisitors: 32 },
    { month: 'Nov', total: 19500, newVisitors: 35 },
    { month: 'Dec', total: 22450, newVisitors: 40 },
];

export const upcomingEvents = [
  {
    title: 'Sunday Morning Service',
    date: 'JUN 23',
    time: '10:00 AM',
    location: 'Main Sanctuary',
  },
  {
    title: 'Youth Group Hangout',
    date: 'JUN 26',
    time: '6:30 PM',
    location: 'Youth Hall',
  },
  {
    title: 'Community Food Drive',
    date: 'JUN 29',
    time: '9:00 AM',
    location: 'Church Parking Lot',
  },
  {
    title: "Men's Breakfast",
    date: 'JUL 01',
    time: '8:00 AM',
    location: 'Fellowship Hall',
  },
];

export const prayerRequests = [
    { id: 1, request: 'Healing for Mary S.', submitted: 'Submitted 2 days ago' },
    { id: 2, request: 'Guidance for the Johnson Family', submitted: 'Submitted 3 days ago' },
    { id: 3, request: 'Job opportunity for David P.', submitted: 'Submitted 5 days ago' },
];

export const membersData = [
    {
      id: 1,
      name: 'John Doe',
      email: 'john.doe@example.com',
      phone1: '+1 234 567 890',
      phone2: '',
      status: 'Active',
      groups: ['Volunteers', 'Choir'],
    },
    {
      id: 2,
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      phone1: '+1 987 654 321',
      phone2: '',
      status: 'Active',
      groups: ['Youth Group'],
    },
    {
      id: 3,
      name: 'Robert Brown',
      email: 'robert.brown@example.com',
      phone1: '+1 555 123 456',
      phone2: '',
      status: 'Visitor',
      groups: ['New Member'],
    },
    {
      id: 4,
      name: 'Emily Davis',
      email: 'emily.davis@example.com',
      phone1: '+1 444 555 666',
      phone2: '',
      status: 'Active',
      groups: ['Volunteers'],
    },
    {
      id: 5,
      name: 'Michael Wilson',
      email: 'michael.wilson@example.com',
      phone1: '+1 777 888 999',
      phone2: '',
      status: 'Inactive',
      groups: [],
    },
  ];

  export const groupData = [
    {
      id: 1,
      name: 'Youth Group',
      members: 12,
      description: 'Weekly meeting for teenagers and young adults.',
      status: 'Active',
    },
    {
      id: 2,
      name: 'Choir',
      members: 25,
      description: 'Leads worship through music on Sundays.',
      status: 'Active',
    },
    {
      id: 3,
      name: 'Volunteers',
      members: 58,
      description: 'General volunteer pool for church events and needs.',
      status: 'Active',
    },
    {
      id: 4,
      name: "Men's Bible Study",
      members: 8,
      description: 'Bi-weekly study sessions for men.',
      status: 'On Hold',
    },
    {
      id: 5,
      name: 'New Members Class',
      members: 15,
      description: 'Orientation class for new church members.',
      status: 'Inactive',
    },
  ];
  
  export const groupMembers = [
    {
      id: 1,
      name: 'Jane Smith',
      email: 'jane.smith@example.com',
      phone: '+1 987 654 321',
      role: 'Leader',
    },
    {
      id: 2,
      name: 'Emily White',
      email: 'emily.white@example.com',
      phone: '+1 234 567 891',
      role: 'Member',
    },
    {
      id: 3,
      name: 'Michael Johnson',
      email: 'michael.j@example.com',
      phone: '+1 555 123 457',
      role: 'Member',
    },
  ];

  export const attendanceRecords = [
    {
        id: 1,
        date: '2024-10-27',
        serviceName: 'Sunday Morning Service',
        memberName: 'John Doe',
        status: 'Present',
        checkInTime: '10:05 AM',
    },
    {
        id: 2,
        date: '2024-10-27',
        serviceName: 'Sunday Morning Service',
        memberName: 'Jane Smith',
        status: 'Present',
        checkInTime: '10:02 AM',
    },
    {
        id: 3,
        date: '2024-10-26',
        serviceName: 'Youth Group Meeting',
        memberName: 'Michael Brown',
        status: 'Absent',
        checkInTime: '-',
    },
    {
        id: 4,
        date: '2024-10-24',
        serviceName: 'Midweek Bible Study',
        memberName: 'Emily Johnson',
        status: 'Excused',
        checkInTime: '-',
    },
    {
        id: 5,
        date: '2024-10-24',
        serviceName: 'Midweek Bible Study',
        memberName: 'David Wilson',
        status: 'Present',
        checkInTime: '7:10 PM',
    },
    {
        id: 6,
        date: '2024-10-20',
        serviceName: 'Sunday Morning Service',
        memberName: 'John Doe',
        status: 'Present',
        checkInTime: '10:03 AM',
      },
      {
        id: 7,
        date: '2024-10-20',
        serviceName: 'Sunday Morning Service',
        memberName: 'Jane Smith',
        status: 'Present',
        checkInTime: '10:01 AM',
      },
      {
        id: 8,
        date: '2024-10-19',
        serviceName: 'Youth Group Meeting',
        memberName: 'Michael Brown',
        status: 'Present',
        checkInTime: '7:05 PM',
      },
      {
        id: 9,
        date: '2024-10-17',
        serviceName: 'Midweek Bible Study',
        memberName: 'Emily Johnson',
        status: 'Absent',
        checkInTime: '-',
      },
      {
        id: 10,
        date: '2024-10-17',
        serviceName: 'Midweek Bible Study',
        memberName: 'David Wilson',
        status: 'Present',
        checkInTime: '7:08 PM',
      },
  ];

  export const events = [
    {
      id: 1,
      title: 'Youth Group',
      category: 'Youth Group',
      date: '2024-10-04T18:30:00',
      time: '6:30 PM - 8:00 PM',
      location: 'Youth Hall',
      address: '123 Church Street, Anytown, USA',
      description: 'A fun night for teens to connect and grow in their faith.'
    },
    {
      id: 2,
      title: 'Sunday Service',
      category: 'Sunday Service',
      date: '2024-10-06T10:00:00',
      time: '10:00 AM - 11:30 AM',
      location: 'Main Sanctuary',
      address: '123 Church Street, Anytown, USA',
      description: 'Join us for our weekly worship service.'
    },
    {
      id: 3,
      title: 'Weekly Bible Study Group',
      category: 'Bible Study',
      date: '2024-10-11T19:00:00',
      time: '7:00 PM - 8:30 PM',
      location: 'Fellowship Hall',
      address: '123 Church Street, Anytown, USA',
      description: "Join us for an in-depth study of the book of Romans. All are welcome, from new believers to seasoned scholars. It's a great opportunity for fellowship and growing in your faith."
    },
    {
      id: 4,
      title: 'Community Outreach',
      category: 'Community Outreach',
      date: '2024-10-10T09:00:00',
      time: '9:00 AM - 12:00 PM',
      location: 'City Park',
      address: '456 Park Avenue, Anytown, USA',
      description: 'Serving our community by cleaning up the local park.'
    },
    {
      id: 5,
      title: 'Sunday Service',
      category: 'Sunday Service',
      date: '2024-10-13T10:00:00',
      time: '10:00 AM - 11:30 AM',
      location: 'Main Sanctuary',
      address: '123 Church Street, Anytown, USA',
      description: 'Join us for our weekly worship service.'
    }
  ];

  export const volunteersData = [
    {
      id: 1,
      name: 'Olivia Chen',
      role: 'Youth Group Leader',
      email: 'olivia.chen@example.com',
      phone: '(555) 123-4567',
      hoursServed: 128,
      nextServing: 'Oct 29, 2023',
      backgroundCheck: 'Passed',
      avatarUrl: 'https://picsum.photos/seed/101/100/100',
      skills: ['Childcare', 'Leadership', 'Public Speaking', 'First Aid Certified'],
      availability: {
        Sunday: [{ time: 'Mornings', available: true }, { time: 'Afternoons', available: false }],
        Wednesday: [{ time: 'Evenings', available: true }],
        Saturday: [{ time: 'All Day', available: true }],
      },
      adminNotes: 'Olivia is a core member of the youth leadership team. Great with teens and very reliable.',
    },
    {
      id: 2,
      name: 'Liam Rodriguez',
      role: 'AV Tech',
      email: 'liam.r@example.com',
      phone: '(555) 987-6543',
      hoursServed: 250,
      nextServing: 'Nov 5, 2023',
      backgroundCheck: 'Passed',
      avatarUrl: 'https://picsum.photos/seed/102/100/100',
      skills: ['Audio Engineering', 'Video Production', 'Lighting'],
      availability: {
        Sunday: [{ time: 'Mornings', available: true }, { time: 'Afternoons', available: true }],
        Wednesday: [{ time: 'Evenings', available: false }],
        Saturday: [{ time: 'Mornings', available: true }],
      },
      adminNotes: '',
    },
    {
        id: 3,
        name: 'Ava Nguyen',
        role: 'Worship Team',
        email: 'ava.n@example.com',
        phone: '(555) 234-5678',
        hoursServed: 312,
        nextServing: 'Oct 29, 2023',
        backgroundCheck: 'Passed',
        avatarUrl: 'https://picsum.photos/seed/103/100/100',
        skills: ['Vocals', 'Guitar', 'Songwriting'],
        availability: {
          Sunday: [{ time: 'Mornings', available: true }, { time: 'Afternoons', available: false }],
          Wednesday: [{ time: 'Evenings', available: true }],
          Saturday: [{ time: 'All Day', available: false }],
        },
        adminNotes: 'Leads worship once a month.',
      },
      {
        id: 4,
        name: 'Noah Patel',
        role: 'Greeter',
        email: 'noah.p@example.com',
        phone: '(555) 345-6789',
        hoursServed: 85,
        nextServing: 'Nov 12, 2023',
        backgroundCheck: 'Passed',
        avatarUrl: 'https://picsum.photos/seed/104/100/100',
        skills: ['Hospitality', 'Communication'],
        availability: {
          Sunday: [{ time: 'Mornings', available: true }, { time: 'Afternoons', available: false }],
          Wednesday: [{ time: 'Evenings', available: false }],
          Saturday: [{ time: 'All Day', available: true }],
        },
        adminNotes: 'Very friendly and welcoming.',
      },
      {
        id: 5,
        name: 'Emma Garcia',
        role: "Children's Ministry",
        email: 'emma.g@example.com',
        phone: '(555) 456-7890',
        hoursServed: 190,
        nextServing: 'Oct 29, 2023',
        backgroundCheck: 'Passed',
        avatarUrl: 'https://picsum.photos/seed/105/100/100',
        skills: ['Childcare', 'Teaching', 'Crafts'],
        availability: {
          Sunday: [{ time: 'Mornings', available: true }, { time: 'Afternoons', available: false }],
          Wednesday: [{ time: 'Evenings', available: false }],
          Saturday: [{ time: 'All Day', available: false }],
        },
        adminNotes: 'Great with the preschoolers.',
      },
  ];