import { z } from 'zod';

const text = z.string().trim().min(1).max(500);
const optionalText = z.string().trim().max(5000).optional().default('');
const churchFields = { churchId: z.string().trim().min(1).optional(), churchName: z.string().trim().min(1).optional() };

export const eventSchema = z.object({ ...churchFields, title: text, description: optionalText, location: optionalText, category: optionalText, startAt: z.string().datetime(), endAt: z.string().datetime().optional(), capacity: z.number().int().min(0).optional(), status: z.enum(['scheduled', 'cancelled', 'completed']).default('scheduled') });
export const ceremonySchema = z.object({ ...churchFields, type: text, date: z.string().datetime(), participants: z.array(z.string().trim().min(1)).min(1), officiant: optionalText, notes: optionalText, status: z.enum(['scheduled', 'completed', 'cancelled']).default('scheduled') });
export const groupSchema = z.object({ ...churchFields, name: text, description: optionalText, category: optionalText, status: z.enum(['active', 'inactive', 'paused']).default('active'), leaderIds: z.array(z.string()).default([]), memberIds: z.array(z.string()).default([]) });
export const volunteerSchema = z.object({ ...churchFields, memberId: z.string().optional(), firstName: text, lastName: text, email: z.string().email().optional().or(z.literal('')), phone: optionalText, primaryRole: optionalText, skills: z.array(z.string()).default([]), availability: optionalText, backgroundCheck: z.boolean().default(false), status: z.enum(['active', 'inactive']).default('active') });
export const volunteerTaskSchema = z.object({ ...churchFields, volunteerId: z.string().optional(), title: text, description: optionalText, dueAt: z.string().datetime().optional(), status: z.enum(['pending', 'in_progress', 'completed', 'cancelled']).default('pending'), priority: z.enum(['low', 'medium', 'high']).default('medium') });
export const volunteerScheduleSchema = z.object({ ...churchFields, volunteerIds: z.array(z.string()).default([]), title: text, startsAt: z.string().datetime(), endsAt: z.string().datetime().optional(), location: optionalText, notes: optionalText });
export const prayerRequestSchema = z.object({ ...churchFields, memberId: z.string().optional(), title: text, description: z.string().trim().min(1).max(5000), privacy: z.enum(['public', 'group', 'staff']).default('public'), groupId: z.string().optional(), status: z.enum(['active', 'answered', 'archived']).default('active') });
export const sermonSchema = z.object({ ...churchFields, title: text, speaker: text, date: z.string().datetime(), series: optionalText, scripture: optionalText, description: optionalText, status: z.enum(['draft', 'published', 'archived']).default('draft') });
export const sermonMediaSchema = z.object({ sermonId: z.string().min(1), type: z.enum(['audio', 'image', 'video']), url: z.string().url(), title: optionalText, mimeType: optionalText, size: z.number().min(0).optional() });
export const facilitySchema = z.object({ ...churchFields, name: text, capacity: z.number().int().min(0), category: text, location: optionalText, amenities: z.array(z.string()).default([]), notes: optionalText, status: z.enum(['available', 'maintenance', 'inactive']).default('available') });
export const facilityBookingSchema = z.object({ ...churchFields, facilityId: z.string().min(1), title: text, startsAt: z.string().datetime(), endsAt: z.string().datetime(), requestedBy: optionalText, notes: optionalText, status: z.enum(['pending', 'confirmed', 'cancelled']).default('confirmed') });
export const financialTransactionSchema = z.object({ ...churchFields, type: z.enum(['income', 'expense']), amount: z.number().positive(), date: z.string().datetime(), category: text, fundId: z.string().optional(), ministryId: z.string().optional(), description: optionalText, reference: optionalText });
export const budgetSchema = z.object({ ...churchFields, year: z.string().regex(/^\d{4}$/), name: text, category: text, planned: z.number().min(0), actual: z.number().min(0).default(0), notes: optionalText });
export const fundSchema = z.object({ ...churchFields, name: text, description: optionalText, balance: z.number().default(0), restricted: z.boolean().default(false), status: z.enum(['active', 'inactive']).default('active') });
export const pledgeSchema = z.object({ ...churchFields, memberId: z.string().optional(), donorName: text, amount: z.number().positive(), frequency: z.enum(['once', 'weekly', 'monthly', 'annual']).default('once'), startDate: z.string().datetime(), endDate: z.string().datetime().optional(), fundId: z.string().optional(), status: z.enum(['active', 'fulfilled', 'cancelled']).default('active'), notes: optionalText });
